SIDO_LIST = [
    {"rnum": 1, "code": "1", "name": "서울", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_82.png"},
    {"rnum": 2, "code": "2", "name": "인천", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_83.png"},
    {"rnum": 3, "code": "3", "name": "대전", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_84.png"},
    {"rnum": 4, "code": "4", "name": "대구", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_85.png"},
    {"rnum": 5, "code": "5", "name": "광주", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_86.png"},
    {"rnum": 6, "code": "6", "name": "부산", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_87.png"},
    {"rnum": 7, "code": "7", "name": "울산", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_88.png"},
    {"rnum": 8, "code": "8", "name": "세종특별자치시", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_89.png"},
    {"rnum": 9, "code": "31", "name": "경기도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_90.png"},
    {"rnum": 10, "code": "32", "name": "강원특별자치도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_91.png"},
    {"rnum": 11, "code": "33", "name": "충청북도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_92.png"},
    {"rnum": 12, "code": "34", "name": "충청남도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_93.png"},
    {"rnum": 13, "code": "35", "name": "경상북도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_94.png"},
    {"rnum": 14, "code": "36", "name": "경상남도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_95.png"},
    {"rnum": 15, "code": "37", "name": "전북특별자치도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_96.png"},
    {"rnum": 16, "code": "38", "name": "전라남도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_97.png"},
    {"rnum": 17, "code": "39", "name": "제주도", "image": "https://kmu-alpha-project-2025.s3.ap-northeast-2.amazonaws.com/image_98.png"},
]